### ISSUE TITLE
AreaVoices Network - PHP Tuning

### ISSUE THREAD

**Issue by rveitch** [openfcci/areavoices-network#17]
Resolve PHP errors noted by New Relic and Dev Console with PHP tuning.
![screenshot521](https://cloud.githubusercontent.com/assets/12876929/12380846/fbcc94d0-bd41-11e5-8e4e-27ae1cb086f9.png)

**Comment by jgrinsteinner** [comment]
@rveitch Network error% reduced form 35% to 1% - Need to keep this open?
