### ISSUE TITLE
Add product match widget to Bison Media Blog and UND Hockey Blog

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#38]
### Overview
Please add this product match widget on the article pages of http://bisonmedia.areavoices.com/ and http://undhockey.areavoices.com/ and associated placement on mobile.

Code Snippets are located in the Reference section:
The top div tag holds all of the parameters you can change. The one thing you’ll need to do is programmatically add the canonical url to ensure the best match for each article.

You may also want to play with the data-take parameter which dictates how many products to pull. I set it to 4 per our conversation, however depending on the size of the space, 3 may work better.

I setup your template parameters to pick up the green from your site and say Shop Now in the button. All of these things, as well as many more can by changed. Feel free to reach out with questions and we have detailed developer documentation here - https://developer.okanjo.com/okanjo-js#okanjo-js

#### Checklist
- [ ] Widget added to [Bison Media Blog](http://bisonmedia.areavoices.com/) `at the bottom of the right hand rail` and associated placement on mobile.
- [ ] Widget added to [UND Hockey Blog](http://undhockey.areavoices.com/) `at the bottom of the story, right before the "Responses" section` and associated placement on mobile.

#### Mockups & Examples

[Bison Media Code:](https://gist.github.com/Corleen/2d2494a303bdc83eb95ad5764d4eb9de)
```js
<div class="product-widget-dropzone" 
   data-mode="sense" 
   data-take="4" 
   data-template-product-main="product.block2"
   data-template-cta-style="button"
   data-template-cta-color="#006633"
   data-url="Programatically add your url here" 
   data-selectors="h1.story-title, div.post-cat-contain, #content-area > p, #content-area > ul"
   data-pools="BisonMedia">
</div>
<script src="https://cdn.okanjo.com/js/latest/okanjo-bundle.min.js" crossorigin="anonymous"></script>
<script>

    // You can set the global key on the okanjo namespace, or you can set it as an option on the widget constructor
    okanjo.key = 'AK18PpKGrMUO8Mp3wj5eYWQwTL6pyBbfj';

    // Create a product widget on the elements with given class
    var targets = okanjo.qwery('.product-widget-dropzone'), i = 0, p = [];
    for ( ; i < targets.length; i++) {
        p.push(new okanjo.Product(targets[i]));
    }

</script>
```

[UND Hockey Code:]()
```js
<div class="product-widget-dropzone" 
   data-mode="sense" 
   data-take="4" 
   data-template-product-main="product.block2"
   data-template-cta-style="button"
   data-template-cta-color="#006633"
   data-url="Programatically add your url here" 
   data-selectors="h1.entry-title, div.entry-content p"
   data-pools="UNDhockey">
</div>
<script src="https://cdn.okanjo.com/js/latest/okanjo-bundle.min.js" crossorigin="anonymous"></script>
<script>

    // You can set the global key on the okanjo namespace, or you can set it as an option on the widget constructor
    okanjo.key = 'AKlb0IhnNwnvYcXvVMv7MvWGsAzAphho';

    // Create a product widget on the elements with given class
    var targets = okanjo.qwery('.product-widget-dropzone'), i = 0, p = [];
    for ( ; i < targets.length; i++) {
        p.push(new okanjo.Product(targets[i]));
    }

</script>
```
![okanjo-bisonmedia-undhockey-splitdiff](https://cloud.githubusercontent.com/assets/12876929/14195754/7bb76402-f782-11e5-9242-2c061efa64bf.png)
### Reference
- [Bison Media Blog Code Snippet](https://gist.github.com/Corleen/2d2494a303bdc83eb95ad5764d4eb9de)
- [UND Hockey Blog Code Snippet](https://gist.github.com/Corleen/f313cd82cc6dd3e068c160ea96741356)
- [Northland Outdoors Blog Code Snippet](https://gist.github.com/Corleen/fe1577f185526483fb420fec45ed312c)
- [Developer Documentation](https://developer.okanjo.com/okanjo-js#okanjo-js)

**Comment by rveitch** [comment]
![okanjo-bisonmedia-undhockey-splitdiff](https://cloud.githubusercontent.com/assets/12876929/14195754/7bb76402-f782-11e5-9242-2c061efa64bf.png)
