### ISSUE TITLE
Impact Magazine: Advertise Page

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#45]
### Overview
We need to create a page for Impact Magazine to highlight options/pricing for prospective advertisers.

#### Checklist
- [x] Create Page
- [x] Add to site navigation

#### Mockups & Examples
First Column
Information about the magazine + Brand Enhancements with IMPACT text

Second Column
Image from the first page of the PDF

Third Column
Print & Digital Pricing

### Reference
- [Northland Outdoors Subscribe Page](http://www.northlandoutdoors.com/subscribe/)
- [Page Text](https://docs.google.com/a/forumcomm.com/document/d/1MmvJooHM77jUsCqZ8PdDeVnj_JRYNMX9xT4zCxqMd8g/edit?usp=sharing)
- [Sales Brochure PDF - Can leverage front page as the image](https://github.com/openfcci/areavoices-network/files/215337/EXTERNAL.ImpactMagazine_2016.4.pdf)

**Comment by jgrinsteinner** [comment]
@bradenfcc I've attached an updated version of the PDF that should be used for this page.
[EXTERNAL ImpactMagazine_2016 (1).pdf](https://github.com/openfcci/areavoices-network/files/223943/EXTERNAL.ImpactMagazine_2016.1.pdf)

**Comment by bradenfcc** [comment]
the link on the advertise page should be updated now.
