### ISSUE TITLE
AreaVoices Ad Tag Update

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#55]
### Overview
Ad Tags for the leaderboard position need to be updated per the below example.

#### Checklist
- [ ] Update tags

#### Mockups & Examples
They currently read:

`gptAdSlots0 = googletag.defineSlot('/7021/fcc.forum/fcc.areavoices', [300, 50], 'leaderboard-ad')`

They should be:

`gptAdSlots0 = googletag.defineSlot('/7021/fcc.areavoices', [300, 50], 'leaderboard-ad')`

**Comment by jgrinsteinner** [comment]
Can we get this updated as soon as possible?

**Comment by rveitch** [comment]
On it.

**Comment by rveitch** [comment]
Updated: http://gitlab.fccinteractive.com/areavoices/areavoices-com/commit/1c688f73192abc188d030fce0993c1e1d3571ecd
