### ISSUE TITLE
Update Quantcast tracking

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#58]
### Overview
We've received a new tracking pixel from Quantcast that will help with ad targeting and hopefully increase some revenue and improve the tracking metrics that Quantcast receives.

#### Checklist
- [ ] Update the code snippet

#### Mockups & Examples
Replace the current code:
`
				<script type="text/javascript">
					_qoptions={qacct:"p-f1gwFa5-x-0VY"};
				</script>
				<script type="text/javascript" src="http://edge.quantserve.com/quant.js"></script>
				<noscript>
					<div><img src="http://pixel.quantserve.com/pixel/p-f1gwFa5-x-0VY.gif" style="display: none;" class="noBorder" height="1" width="1" alt="Quantcast"/></div>
				</noscript>
			`

With this code:
[Quantcast pixel.txt](https://github.com/openfcci/areavoices-network/files/260263/Quantcast.pixel.txt)

### Reference
- [#](Link)

**Comment by rveitch** [comment]
The code has been updated and is now live.

- https://github.com/openfcci/fcc-tracking-code-manager/commit/15cee488578bbbda3837f81212cb12c6b82eedc7
- http://gitlab.fccinteractive.com/areavoices/areavoices-com/commit/e898c4e80e9a00d9420421840051ec173288da59
