### ISSUE TITLE
Northland Outdoors: Additional Subscription Page Updates

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#68]
### Overview
A few more updates for the NO Subscribe page. Let me know if you need Mailchimp values for these items.

#### Checklist
- [x] Remove the Country field
- [x] Add a field for Business Name (not required)
- [x] Add a field for Phone Number (not required)

### Reference
- [#](Link)

**Comment by bradenfcc** [comment]
all fields should be added and updated on the subscribe page

**Comment by rveitch** [comment]
@jgrinsteinner Review?
