### ISSUE TITLE
Say Anything Blog Issues

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-network#75]
### Overview
Couple of small issues with the SAB theme: The captions are interfering with the section page layout, and the Pull Quotes are displaying oddly on mobile (screenshots attached).

#### Checklist
- [x] Fix the image/caption layout for section pages
- [x] Fix the Pull Quote display for articles on mobile

#### Mockups & Examples
![screenshotarchive](https://cloud.githubusercontent.com/assets/17886062/15822561/20b2c830-2bbc-11e6-9812-3ce84bfe7d2a.png)
<img width="879" alt="screenshot 2016-06-02 13 29 01" src="https://cloud.githubusercontent.com/assets/17886062/15822584/4394ba3e-2bbc-11e6-9241-7cb75665302a.png">

### Reference
- [https://www.sayanythingblog.com/entry/category/north-dakota-2/](North Dakota Section Page)

**Comment by rveitch** [comment]
## Featured Image Section Caption Fix

![image](https://cloud.githubusercontent.com/assets/12876929/15829677/544fe20e-2bda-11e6-9f05-4e92576cffb0.png)

## Pull Quote Mobile Fix

![image](https://cloud.githubusercontent.com/assets/12876929/15829638/26f842a6-2bda-11e6-9f9b-093cbaa5d70b.png)
